## Replicate runner for the simulation studies.
##
## Three things this does that a bare `for` loop or `replicate()` does not.
##
## Seeds. Each replicate gets its own L'Ecuyer-CMRG stream derived from one
## master seed, so replicate 4171 of scenario 12 draws the same data whether the
## run happened on 1 core or 8, in one sitting or resumed after a crash. A study
## whose results depend on the core count is not reproducible, and `set.seed(i)`
## inside a loop gives streams that are not guaranteed independent.
##
## Failures. A replicate that errors, or on which a method does not converge, is
## recorded and the run continues. Failures are data: a method that fails on the
## hard end of a factor is telling you something, and a harness that aborts on
## the first error hides exactly the scenarios worth reporting.
##
## Checkpoints. Results are flushed per scenario, so an interrupted run resumes
## instead of restarting.

suppressPackageStartupMessages({
  library(future)
  library(furrr)
})

## Build independent RNG streams from one master seed.
##
## Streams are generated by advancing the L'Ecuyer-CMRG state, which guarantees
## the substreams do not overlap. Indexing is global across the whole design, so
## scenario 3 replicate 1 and scenario 4 replicate 1 do not share data; that
## matters because common random numbers across scenarios would induce
## correlation the performance measures do not account for.
make_streams <- function(n, master_seed) {
  rng <- RNGkind()
  on.exit(RNGkind(rng[1], rng[2], rng[3]), add = TRUE)
  RNGkind("L'Ecuyer-CMRG")
  set.seed(master_seed)
  s <- .Random.seed
  out <- vector("list", n)
  for (i in seq_len(n)) {
    out[[i]] <- s
    s <- parallel::nextRNGStream(s)
  }
  out
}

## Run one replicate under its own stream, catching anything that goes wrong.
##
## `fn` receives the scenario row (a one-row data frame) and must return a data
## frame of results, one row per method. Warnings are captured too: a
## non-convergence warning from a fitting routine is the usual way a PAIC
## estimator tells you its answer is not to be trusted, and losing it means
## treating a bad fit as a good one.
run_one <- function(fn, scenario, rep_id, stream) {
  assign(".Random.seed", stream, envir = .GlobalEnv)
  warns <- character(0)
  t0 <- proc.time()[["elapsed"]]
  res <- withCallingHandlers(
    tryCatch(fn(scenario, rep_id), error = function(e) {
      structure(list(), class = "sim_error", message = conditionMessage(e))
    }),
    warning = function(w) {
      warns <<- c(warns, conditionMessage(w))
      invokeRestart("muffleWarning")
    }
  )
  secs <- proc.time()[["elapsed"]] - t0

  if (inherits(res, "sim_error")) {
    return(data.frame(rep = rep_id, method = NA_character_, est = NA_real_,
                      error = attr(res, "message") %||% "error",
                      warnings = paste(warns, collapse = " | "),
                      secs = secs, stringsAsFactors = FALSE))
  }
  res$rep <- rep_id
  res$error <- NA_character_
  res$warnings <- if (length(warns)) paste(warns, collapse = " | ") else NA_character_
  res$secs <- secs
  res
}

`%||%` <- function(a, b) if (is.null(a)) b else a

## Run the full design.
##
## `scenarios` is a data frame, one row per scenario, with whatever columns the
## data-generating mechanism needs. `fn(scenario, rep_id)` returns one row per
## method with at least `method` and `est`.
##
## Results are written to `outdir/raw/scenario-NN.rds` as each scenario
## finishes. Those files are regenerable from the seed and are gitignored; the
## tracked artifact is the summary CSV the analysis step writes.
run_design <- function(fn, scenarios, n_rep, master_seed, outdir,
                       workers = max(1L, parallel::detectCores() - 2L),
                       resume = TRUE) {
  raw <- file.path(outdir, "raw")
  dir.create(raw, recursive = TRUE, showWarnings = FALSE)

  n_scen <- nrow(scenarios)
  streams <- make_streams(n_scen * n_rep, master_seed)

  plan(multisession, workers = workers)
  on.exit(plan(sequential), add = TRUE)

  message(sprintf("%d scenarios x %d replicates on %d workers",
                  n_scen, n_rep, workers))

  for (s in seq_len(n_scen)) {
    f <- file.path(raw, sprintf("scenario-%03d.rds", s))
    if (resume && file.exists(f)) {
      message(sprintf("  scenario %d/%d: cached", s, n_scen))
      next
    }
    idx <- (s - 1L) * n_rep + seq_len(n_rep)
    scen <- scenarios[s, , drop = FALSE]
    t0 <- proc.time()[["elapsed"]]
    res <- future_map(
      seq_len(n_rep),
      function(i) run_one(fn, scen, i, streams[[idx[i]]]),
      .options = furrr_options(seed = NULL, globals = TRUE)
    )
    res <- do.call(rbind, res)
    res <- cbind(scen[rep(1L, nrow(res)), , drop = FALSE], res)
    rownames(res) <- NULL
    saveRDS(res, f)
    fails <- sum(!is.na(res$error))
    message(sprintf("  scenario %d/%d: %.0fs, %d replicate errors",
                    s, n_scen, proc.time()[["elapsed"]] - t0, fails))
  }

  do.call(rbind, lapply(sort(list.files(raw, "^scenario-.*\\.rds$",
                                        full.names = TRUE)), readRDS))
}

## Record exactly what produced a result set.
##
## Written next to the results and quoted in the manuscript. Without it a
## simulation is not reproducible in any useful sense: `multinma` 0.9.1 and
## 0.9.1.9002 are different estimators, and a result that changes between them
## is a finding rather than a nuisance.
write_provenance <- function(outdir, packages = character(0), extra = list()) {
  si <- utils::sessionInfo()
  pk <- unique(c("base", packages))
  vers <- vapply(pk, function(p)
    tryCatch(as.character(utils::packageVersion(p)), error = function(e) NA_character_),
    character(1))
  lines <- c(
    "# Provenance",
    "",
    sprintf("R: %s", si$R.version$version.string),
    sprintf("Platform: %s", si$platform),
    sprintf("Running under: %s", si$running),
    "",
    "## Packages",
    "",
    "| package | version |",
    "| --- | --- |",
    sprintf("| %s | %s |", pk, vers),
    ""
  )
  if (length(extra)) {
    lines <- c(lines, "## Run", "",
               sprintf("- **%s**: %s", names(extra), unlist(extra)), "")
  }
  writeLines(lines, file.path(outdir, "provenance.md"))
  invisible(lines)
}
